#version: '3'
#
#services:
#  mysql:
#    container_name: todolist_db
#    image: mysql/mysql-server:5.7
#    environment:
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_DATABASE: "todolist_db"
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      TZ: 'Asia/Seoul'
#    ports:
#      - "3306:3306"
#    command:
#      - "mysqld"
#      - "--character-set-server=utf8mb4"
#      - "--collation-server=utf8mb4_unicode_ci"

version: '3'

services:
  database:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  application:
    container_name: board_vue_backend
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network:
