#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/todolist
#spring.datasource.username=todolist
#spring.datasource.password=todolist
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true

spring:
  batch:
    job:
      enabled: false
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
#  main:
#    web-application-type: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useCursorFetch=true
    username: root
    password: doseong9114!!


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: ehtjd33@gmail.com
    password: zmgoccjzlfqowudj
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 326554605996-ujphf2on3dhf6iqsq8l9dkmfed4fmmqm.apps.googleusercontent.com
            client-secret: 6W7DOAVaiHoabm-8wuLG6qPc
            scope:
              - email
              - profile

          facebook:
            client-id: 532196661426439
            client-secret: ba907d1d1d6ef00434fe58806a632825
            scope:
              - email
              - public_profile

logging:
  level:
    org.hibernate.SQL: debug